### ISSUE TITLE
File encoding (revisiting #10)

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/hyphen-la#16]
RE: #10.

So, after doing some research and testing, it appears that at least as far as `stdin` and `stdout` are concerned, setting `PYTHONIOENCODING="utf8"` as an environment variable will enable the syllabifier to work (i.e. use UTF-8 ecoding) under a restricted shell where it would otherwise not (i.e. use US-ASCII).

However, this does not apply to files.  For that the "fix" appears to be to specify the `encoding` argument for `open` when accessing the file.

For my own use case, fixing `stdin` and `stdout` with the environment variable is sufficient.  If I'm trying to operate on files, then I'm working from my normal shell environment where Python can pick-up the necessary encoding automatically.  Inside the restricted shell where the problem occurs I'm always using `stdin` and `stdout`.

So, unless there are others out there who are having a file encoding problem, I'm not going to worry about this any more.  I'm opening this issue to provide a place for individuals with a file encoding problem to post about their problem and let me know that I need to revisit this decision.

**Comment by rpspringuel** [comment]
Hmm... You know I never thought of explicitly setting `LANG` myself.  I don't know why, as it seems to be an obvious thing to try now that you mention it.  And indeed, when I try it, it works for files as well as `stdin` and `stdout`.  Awfully big blindspot to have missed that.

**Comment by eroux** [comment]
maybe this could be closed?

**Comment by rpspringuel** [comment]
Sure.
