### ISSUE TITLE
abstulit - ábstulit

### ISSUE THREAD

**Issue by fradec** [gregorio-project/hyphen-la#19]
abstulit is correctly hyphened in abs-tu-lit, but the accented word is hyphened in ábstu-lit, while Claudio's file, [line 197](https://github.com/gregorio-project/hyphen-la/blob/master/tests/proofreading-Claudio-2.txt#L197), gives correct hyphenation.
How to solve the problem? Just copy the accented word into one of the 'Solesmes' accented files? Or should we manage to group all the words in a single file to track duplicates?

**Comment by fradec** [comment]
Or is the problem with patterns?
It would then miss an entry for ábstulit?

**Comment by eroux** [comment]
Claudio's file is not run in the `test.py` file, so if you want to test this word you should add it in one of the accented solesmes files yes. Now, if the result is incorrect, then an additional pattern is needed indeed.

**Comment by fradec** [comment]
Ok, your solution is good: i have added abstulit and ábstulit, to Solesmes 3 and one pattern: .ábs3tu which seem to be sufficient. But would I complete the list with all the forms of abstul…?

**Comment by eroux** [comment]
If you're unsure, don't hesitate to add all the forms in the test file, maybe this will reveal other missing patterns

**Comment by fradec** [comment]
I will update the other branch as soon as possible.

**Comment by eroux** [comment]
Regarding what you did in https://github.com/gregorio-project/hyphen-la/commit/1d58e0be7d2e0fca624eba1fbaa3ba734bf383cb :
- the alphabetical order should be kept for the sake of simplicity, so the new pattern should be around line 77, not line 1
- I think that for the sake of consistency with lines 77-78, `.áb4s3tu` would be safer

**Comment by fradec** [comment]
Ok, you're right. I changed everything according to your instructions, and added the other forms in the list, "cela ne mange pas de pain", and since it's done…
