### ISSUE TITLE
Format-specific tools

### ISSUE THREAD

**Issue by igneus** [gregorio-project/hyphen-la#2]
If someone wants to build a format-specific hyphenator e.g. for lilypond or gabc, do you prefer to put it here in the one package, or to make hyphen-la an installable Python library and make the format-specific tools separate applications depend on it?

**Comment by eroux** [comment]
I think it would be best to keep it separate, in my mind `hyphen-la` is mainly a repository for the (ongoing) pattern development and proofreading, the syllabifier is just a (not so) silly example used for testing, there won't be any packaged python library in the repository. So softwares using the patterns should have a copy of the patterns in their repo, or include `hyphen-la` as submodule... At least that's the way I see it now, I'm open to discussion! If you want to create a repo in https://github.com/gregorio-project/ just ask, I'll create one and give you admin rights.

**Comment by igneus** [comment]
Thanks for clarification.
