### ISSUE TITLE
sp block

### ISSUE THREAD

**Issue by fradec** [gregorio-project/hyphen-la#24]
While working on question [#23]( #23 ), I touched on a larger and more complex problem, that of the break around the *sp* block. I have done a vast search through the dictionary (Goelzer) of all the Latin words that contain this block. I only listed the input forms of the dictionary, except for the verbs for which I added the infinitive. That's what it gives:

- about 930 words are concerned (the number of accented words is around 980)
- approximately 500 words begin with *sp* (purely indicative since they are not concerned by hyphenation)
- the number of errors in the tests with the complete list of words (accented or not) added is about 170
- there are currently 52 pattern patterns that concern *sp*

I propose to review all the patterns affecting the *sp* block to get the least possible errors. A search allowed me to estimate circa 70 patterns will be necessary instead of the 52 existing ones to get the most reliable results possible.

**Comment by fradec** [comment]
The number of existing patterns is actually a bit higher: here are the ones I found, numbering 61:

- 2sp
- .a3s2p
- .a4s3per
- .a4s3pid
- .a5s4perg
- .a5s4pern
- .con3s2p2
- .cu4sp
- .cón3s2p2
- .de3s2p
- .di5s4pe
- .di5s4pi
- .di5s4pé
- .di5s4pí
- .di6s5pen
- .di6s5per
- .di6s5pén
- .di6s5pér
- .di7s6perg
- .di7s6pers
- .di7s6pérg
- .di7s6pérs
- .dispe4r5e
- .dispe4r5i
- .dispé4r5e
- .dispé4r5i
- .dé3s2p
- .exs2p
- .haru3s4p
- .harú3s4p
- .in3s2p
- .inte2r3s4pe
- .inte2r3s4pé
- .intro3s4p
- .pe2r3s2p
- .pro3s2p
- .præ3s2p
- .pró3s2p
- .re3s2p
- .re3s2pec
- .re3s2péc
- .re4s3pu4b3l4ic
- .re4s3pú4b3l4ic
- .ré3s2p
- .su3s2pec
- .su3s2pic
- .su3s2pir
- .su3s2péc
- .su3s2píc
- .su3s2pír
- .su4s3pen
- .su4s3pén
- .supe2r1a3s2p
- .supe2r3s2p
- .supé2r1a3s2p
- .sú3s2pic
- .the3s2p
- .á3s2p
- .á4s3per
- .á4s3pid
- .éxs2p

**Comment by fradec** [comment]
The systematic revision will only add a dozen if all is well.

**Comment by fradec** [comment]
I just pushed the changes. The new test words are not all correct, but not new patterns; all the errors indeed concern other issues.
Here is the log:
```
differences in proofreading-Solesmes-1.txt:


differences in proofreading-Solesmes-2.txt:


differences in proofreading-Solesmes-3.txt:
dispereo 		% dis-per-e-o  (not dis-pe-re-o)
dispereo 		% dis-per-e-o  (not dis-pe-re-o)
disperire 		% dis-per-i-re  (not dis-pe-ri-re)
dyspnœa 		% dys-pnœ-a  (not dysp-nœ-a)
leucaspis 		% leu-cas-pis  (not le-u-cas-pis)
neurospastos 		% neu-ros-pas-tos  (not ne-u-ros-pas-tos)
pheuxaspidion 		% pheu-xas-pi-di-on  (not phe-u-xas-pi-di-on)
præexspectare 		% præ-ex-spec-ta-re  (not præ-e-x-spec-ta-re)
præexspecto 		% præ-ex-spec-to  (not præ-e-x-spec-to)
pseudosphex 		% pseu-do-sphex  (not pseu-dos-phex)
redexspectare 		% red-ex-spec-ta-re  (not re-de-x-spec-ta-re)
redexspecto 		% red-ex-spec-to  (not re-de-x-spec-to)
superaspergere 		% su-per-a-sper-ge-re  (not su-pe-ra-sper-ge-re)
superaspergo 		% su-per-a-sper-go  (not su-pe-ra-sper-go)


differences in proofreading-diphtongues.txt:


differences in proofreading-Flavigny-text-1.txt:


differences in proofreading-Flavigny-2.txt:


differences in proofreading-Solesmes-1-accents.txt:
result without accent (correct) / result with accent (incorrect)


differences in proofreading-Solesmes-2-accents.txt:
result without accent (correct) / result with accent (incorrect)


differences in proofreading-Solesmes-3-accents.txt:
result without accent (correct) / result with accent (incorrect)
dyspnœ́a 		% dysp-nœ-a  (not dysp-nœ́a)
pseudósphex 		% pseu-dos-phex  (not pse-u-dós-phex)
```

**Comment by fradec** [comment]
Only the word *dyspnœa* (*dys-pnœ-a*, of the same family as *a-pnea*) may pose an eternal problem because of the accented *œ*. Given the scarcity of the word, I think it can be dismissed without problem.

**Comment by eroux** [comment]
I'm not sure there's a problem with the accented œ, what would that problem be?

**Comment by fradec** [comment]
I tried a special pattern for this word: `.dy6s5p6n` but either the accented version was broken or it was the unaccented version

I tried a special pattern for this word (`.dy6s5p6n`) that works for the non-accented word but not for the accented one.
The same pattern split in two (`.dy6s5p6nœ́` and `.dy6s5p6nœ`) does not work for the accented one. The *a* sticks to the *œ*.

The question of *œ* followed by a vowel should be explored. I'll be able to watch tomorrow maybe.

**Comment by eroux** [comment]
I'm sure we can add a few patterns to fix it, œ́ is just a sequence of two characters, nothing special...

**Comment by fradec** [comment]
The other errors to be corrected concern:

- `pseudo-` or `eu`
- `pn`
- `ex`
- `pereo`
- `red-`
- `super-`

all require more words for the test.

**Comment by fradec** [comment]
Now, log is:
```
differences in proofreading-Solesmes-3.txt:
dispereo 		% dis-per-e-o  (not dis-pe-re-o)
dispereo 		% dis-per-e-o  (not dis-pe-re-o)
disperire 		% dis-per-i-re  (not dis-pe-ri-re)
leucaspis 		% leu-cas-pis  (not le-u-cas-pis)
neurospastos 		% neu-ros-pas-tos  (not ne-u-ros-pas-tos)
pheuxaspidion 		% pheu-xas-pi-di-on  (not phe-u-xas-pi-di-on)
præexspectare 		% præ-ex-spec-ta-re  (not præ-e-x-spec-ta-re)
præexspecto 		% præ-ex-spec-to  (not præ-e-x-spec-to)
redexspectare 		% red-ex-spec-ta-re  (not re-de-x-spec-ta-re)
redexspecto 		% red-ex-spec-to  (not re-de-x-spec-to)
superaspergere 		% su-per-a-sper-ge-re  (not su-pe-ra-sper-ge-re)
superaspergo 		% su-per-a-sper-go  (not su-pe-ra-sper-go)


differences in proofreading-Solesmes-3-accents.txt:
result without accent (correct) / result with accent (incorrect)
pseudósphex 		% pseu-do-sphex  (not pse-u-dó-sphex)

**Comment by fradec** [comment]
I close this issue, since the problem is fixed. I will open specific tickets for other problems
