### ISSUE TITLE
super-

### ISSUE THREAD

**Issue by fradec** [gregorio-project/hyphen-la#28]
Compound words should be proofread with the prefix `super` to check the place of the hyphenation before or after the `r`.

```
differences in proofreading-Solesmes-3.txt:
superaspergere 		% su-per-a-sper-ge-re  (not su-pe-ra-sper-ge-re)
superaspergo 		% su-per-a-sper-go  (not su-pe-ra-sper-go)
```

**Comment by fradec** [comment]
Circa 140 patterns concerned…

**Comment by fradec** [comment]
There are about 365 entries in the dictionary for `super-`, 14 (with their conjugations or declensions) are hyphenated in `su-pe-r…`. On the totality of forms listed for the moment (circa 1200), only 4 come into conflict:

- `superes` (supe-ro vs super-sum)
- `supereris` (supe-ro vs super-sum)
- `superi` (supe-rus vs super-eo)
- `superis` (supe-rus vs super-eo) For this form only, the accented version can be the difference: `su-pe-ré-ris` vs `su-pér-e-ris`.

For these 4 words, we should see what solution to favor. Maybe depending on the frequency? Documenting the difference in any case will be necessary (maybe in doc folder?).

Otherwise the distinctions are relatively easy, it is about working methodically and patiently, and I am coming to the end of the systematic review.

**Comment by eroux** [comment]
these should be documented in a new file in the doc/ folder indeed, thanks a lot!

**Comment by fradec** [comment]
For `superes`, it is better to privilege `supersum` compared to `supero`: we only find the term once in the Neo-Vulgate (for supersum), and once in existing corpus (Iesus nostra redemptio)
→ su-per-es
→ sú-per-es

For `supereris`, there is no occurrence in corpus. Difference stay in accented versions
→ su-pe-ré-ris
→ su-pe-re-ris
→ su-pér-e-ris

For `superi` and `superis,` it is better to privilege `superus` compared to `supereo:` 5 occurrences in corpus found, all for `superus`. And the classical Latin usage means *Ancients* under this term.
→ su-pe-ri
→ su-pe-ris
→ sú-pe-ri
→ sú-pe-ris

These terms will be classified in a separate file and the choices made will be documented.

**Comment by wehro** [comment]
*supercomedo* should be hyphenated `su-per-com-e-do`, as the last element ist *edo* (to eat).

**Comment by fradec** [comment]
Correction made. I'll push a set of minor fixes before the end of the day
