### ISSUE TITLE
Appropinquant

### ISSUE THREAD

**Issue by bbloomf** [gregorio-project/hyphen-la#3]
Appropinquant syllabifies as ap-pro-pin-qu-ant rather than as ap-pro-pin-quant

**Comment by eroux** [comment]
Thanks a lot for this! I'll add these two words in one of the [lists](https://github.com/gregorio-project/hyphen-la/tree/master/tests), in order not to open too many issues, you can make a

- [ ] list
- [x] like
- [ ] that

that I can update when I fix words

**Comment by bbloomf** [comment]
OK.  I just wrote a script to go through all the GABC files that my propers
tool uses from GregoBase and re-syllabify them based on these
syllabification rules.  These two words were the only ones that syllabified
to a different number of syllables.  But there were a half dozen or so
typos that I found on GregoBase in this manner, where the mistake in how
many syllables was on that end.

I had only noticed the one word at first, or I would have put them both in
the same issue.

*Ben Bloomfield*

**Comment by eroux** [comment]
Ok, thanks! Don't hesitate to add words for which you have doubts about the hyphenation output, we can check them. Also, you can edit the initial message of this issue and add other words, that's not a problem

**Comment by OldClaudio** [comment]
La césure ap-pro-pin-qu-ant est en violation de la règle que `u' après 
`q' est toujours une semi consonne (voire document EG-syllabation.pdf en 
annexe}. Donc pour la grammaire cette césure est erronée, mais pur le 
chant peut être qu'elle soit correcte, car en chantant un utilise 
beaucoup des hiatus qu'en écrivant et en parlant normalement on prononce 
seulement comme diphtongues. Donc cette ci peut être ajoutée à la liste 
des exceptions.
Claudio
