### ISSUE TITLE
a few patterns to test

### ISSUE THREAD

**Issue by eroux** [gregorio-project/hyphen-la#30]
Some words are wrongly hyphenated in the non-liturgical patterns, they should be tested with the liturgical patterns too:

Arachne
cedrus
corruptrix
currus
Daphne
genuit
longaevus
neglego
nescio
animadverto
Ioseph
rhythmicus
rhythmus

**Comment by fradec** [comment]
At the moment, the results are:

- correct:

ce-drus
cor-rup-trix
cur-rus
ge-nu-it
lon-gæ-vus
ne-gle-go
ne-sci-o
a-nim-ad-ver-to
Io-seph

- incorrect

A-ra-ch-ne → A-rach-ne
Da-ph-ne → Daph-ne
rhy-thmi-cus → rhyth-mi-cus
rhy-thmus → rhyth-mus

problems are all related to `h` + `m` or `n` and concerned between 120 and 130 words of the Gaffiot.

**Comment by fradec** [comment]
It should be ok now.

**Comment by eroux** [comment]
excellent, thanks a lot!

**Comment by fradec** [comment]
It's a good question. You are right: the phonetic hyphenation on the one hand and the morphological (and etymological) hyphenation on the other hand.

This is the principle of liturgical hyphenation patterns: they are neither completely etymological nor completely phonetic (see the doc for more details). In this case for `longævus`, the hyphen before the `g` is necessary to keep the sound `dʒe`, which would probably not have been the case with `a`, `o` or `u`.

It is the same as the systematic hyphenation before `sc` when it is followed by `æ`, `e`, `i` or `œ`, even if the etymology does not want it, as in `discedo` for example, which comes from `cedo`.

That said, if you find other examples with a `g`, it would be a good thing to revisit the issue further.

**Comment by wehro** [comment]
OK, this principle is comprehensible.

**Comment by eroux** [comment]
Just to add my 2c: we're talking here about liturgical patterns only; they correspond to the phonetics of XXIth century official liturgical Latin phonetics, sounding like Italian. In this accent, `gæ` is pronounced `d͡ʒe`, and we made the choice not to cut `d͡ʒ`, `ʃ` (ex: `sce`) and `t͡ɕ` (ex: `ci`) from their following vowels. With other patterns, corresponding to other accents or principles, this would be different.
