### ISSUE TITLE
obscurus

### ISSUE THREAD

**Issue by fradec** [gregorio-project/hyphen-la#32]
In my general review of words beginning with `ob`, I have indicated the hyphenation `ob-scurus` (plus derivatives ans compounds).

There is a dilemma here about the priority to be given between etymology and phonetic. The case is different from that of the preservation of the group `sc + e` (and others), as in `di-scedo`, for which we privileged phonetic. Here, in fact, the sound is *hard* and we therefore pronounce `obs-curus` regardless of the place of the hyphen.

So it might be better to correct patterns?

**Comment by wehro** [comment]
I am not sure, but you should consider similar cases like “ab-stare”, “di-stare”, “di-stinguo”, and “su-spicio” at the same time.

**Comment by fradec** [comment]
Those hyphenation problems are more related to the `abs` issue. For this question, there is a choice to do between phonetic and etymology, while `st` or `sp` are only etymological issues. 

Please, note also that all the words with the `sp` block have already been reviewed, and so are, in principle at least all properly scored. `suspicio` is a compound of `su(b)` + `specio`.

However, your suggestions are good, and I would like, over times, to systematically review all occurrences of `st`, but it is a very big job (over 4000 words) that will take time. For the moment, the `str` sequence has already been validated, but there is still a lot of work.

I would also like to add systematic revisions of the words starting with the most common forms of the most common (`ab`, `ad`, `in`, `per`, ...). It's all about time.

**Comment by fradec** [comment]
I modified the patterns for `obscurus` by separating the `s` and the `c` when it is followed by `u`.

It is a choice that is made, not a strict rule. It gives two more patterns.

**Comment by fradec** [comment]
`obscurus` done.
