### ISSUE TITLE
ngu

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#34]
Is there any rule for distinguishing vocalic and semivocalic u in words with `ngu` + vowel? `liturgical-hyphenation.md` states that “langueo” and “languesco” have a semivocalic u, but “langui” and “languere” a vocalic one.
The patterns yield “lan-gue-o”, “lan-gues-co”, “lan-gue-re” and “lan-gu-i”.

**Comment by eroux** [comment]
What I remember from our conversations is that there are rules with many exceptions so the best strategy is to find sources that will allow building long boring lists of hyphenated words. BTW, [Collatinus](https://github.com/biblissima/collatinus) has proven quite an useful tool and there were contributions to Collatinus from this project. It's used to get all the morphologies of a word, and has some good data about accents.

**Comment by fradec** [comment]
In fact the rules are very clear for the group `ngu + vowel`. Everywhere `gu` is a semi vowel, except at the times of the Latin *perfectum* where `gu` is a full vocal (like in `langui`), or before a consonant.

**Comment by wehro** [comment]
I see. So the liturgical patterns are correct, but the documentation is mistaken about `languere`?

**Comment by fradec** [comment]
No, the documentation does not seem to me to be wrong. *Languere* is an homograph:

- infinitive of `langueo`, thus `lan-gue-re`, which was retained for the patterns,
- second form of the third person plural of the *perfectum* of `languesco`, therefore `lan-gu-e-re`. The first form is `languerunt`.

**Comment by wehro** [comment]
OK. I have tried to make it more clear in `liturgical-hyphenation.md`. Please check if it's all right.

**Comment by fradec** [comment]
Perhaps it would be even more clear formulated as follows for line 64:
**ngu:** `u` is a full vowel before a consonant (ex…). Before another vowel, `u` is a full vowel for *perfectum* times (ex…), `u` is a semi vowel in other cases (ex…).

What do you think about this?

**Comment by wehro** [comment]
Thank you. I think the description of ngu is complete now.
