### ISSUE TITLE
su + vowel

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#35]
My Latin grammar states that an unstressed *u* preceded by *s* and followed by a vowel is semivocalic, e.g. *Suēbi*. Another grammar that I have consulted does not mention this rule but states that *u* is semivocalic as an exception in the words *suāvis*, *suādeō*, *suēscō*, *Suēbi*.

`liturgical-hyphenation.md` does not mention these cases and the current liturgical patterns treat *u* as a full vowel in all of these words. This should probably be changed.

**Comment by fradec** [comment]
For the liturgical patterns, it is not the case, it not not of semi vowel. Thus, if it must be documented in `liturgical-hyphenation.md`, I think that it should make it only for information to say that it is valid only in other sets of patterns.

Thus, the liturgical patterns do not have to be modified in my opinion.

**Comment by wehro** [comment]
I did not know that this rule isn't applied to liturgical Latin. I have added a "pitfall" to `liturgical-hyphenation.md`.
