### ISSUE TITLE
puleium, Gaius

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#36]
According to the general rule for semi-consonantic *i* stated in `liturgical-hyphenation.md`, the *i* in *puleium* and *Gaius* is not a full vowel. The current liturgical patterns yield `pu-le-i-um` and `Ga-i-us`, but it should be `pu-le-ium` and `Ga-ius`. The result for *Pompeius* is already correct: `Pom-pe-ius`.

**Comment by fradec** [comment]
The *Gaffiot* gives well the `i` as a `j`, also in `puleiatum` and `puleiatus`, without any counter-example for words beginning by `pulei-`. 

No more problems for `Gaius`: we have also `Gaia` and `Gaianus`, all the words that start with `gai-`. 

This is the case of 4 additional patterns I think.
