### ISSUE TITLE
Iulus, Iuleus

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#37]
The proper noun *Iulus* and the adjective *Iuleus* have a vocalic *I*. They should be hyphenated `I-u-lus` and `I-u-le-us` with the liturgical patterns.

**Comment by fradec** [comment]
With the forms declined, there are 24 words concerned: 
`Iule`, `Iulea`, `Iuleæ`, `Iuleam`, `Iulearum`, `Iuleas`, `Iulee`, `Iulei`, `Iuleis`, `Iuleo`, `Iuleorum`, `Iuleos`, `Iuleum`, `Iuleus`, `Iuli`, `Iulida`, `Iulide`, `Iulidem`, `Iulidi`, `Iulidis`, `Iulis`, `Iulo`, `Iulum`, `Iulus`.

Words beginning with `Iul-` where *I* is put for *J* are 3, there 22 words concerned:
`Iulia`, `Iuliæ`, `Iuliam`, `Iuliane`, `Iuliani`, `Iuliano`, `Iulianum`, `Iulianus`, `Iuliarum`, `Iulias`, `iulicæ`, `iulicarum`, `iulicas`, `iulicis`, `Iulie`, `Iulii`, `Iuliis`, `Iulio`, `Iuliorum`, `Iulios`, `Iulium`, `Iulius`

There are no conflicts, I will refine the patterns for greater accuracy.
