### ISSUE TITLE
Compounds of iacio

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#41]
There are two orthographic variants of the compounds of *iacio*: a classical one ending in *-icio* and a medieval one ending in *-jicio*. A variant ending in *-iicio* is not in use.
It should be taken care that the liturgical patterns as well as the test files `wordlist-liturgical.txt` and `wordlist-liturgical-accents.txt` take into account both variants of words like *abicio*, *adicio*, *eicio*, *inicio*, *obicio*, *subicio* etc.
Currently, the patterns are fine, but the test files contain many forms with the wrong *-iicio* spelling.

**Comment by wehro** [comment]
I was able to correct the test files with the aid of a regular expression.

**Comment by fradec** [comment]
Thank you so much! I reopen the issue, because by running the test script, there are errors that appear, I correct them.

**Comment by fradec** [comment]
Great! The corrections allowed me to gain about 20 patterns, made useless with your cleaning. Thank you so much.
