### ISSUE TITLE
induo

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#43]
The etymology of *induo/induere* is unclear. I recommend to replace `ind-u-o` by `in-du-o` as there is no verb *uo/uere*. Even if *induo* is derived from *ind*, the following *uo* has to be considered as some kind of ending and not as a second part of a compound.

**Comment by fradec** [comment]
The etymology is not a problem I think. It is the same for `induo` and `exuo`, derived from the ancient verb `uo`, to clothe.

In my opinion, if we find that this etymology is problematic for `induo`, and that we put the hyphens `in-du-o`, it will not be very coherent with `ex-u-o`, which will never be cut `e-xu-o`.

The rule applied for liturgical Latin is to cut after the epenthesis as for `red-eo` for example.

So I think the patterns do not have to be changed.

**Comment by fradec** [comment]
> Even if induo is derived from ind, the following uo has to be considered as some kind of ending and not as a second part of a compound.

That is certain is that `induo` is not derived from `ind`, but a compound of `in` + `uo`.

**Comment by wehro** [comment]
To be consequent, *indumentum* should be hyphenated as `ind-u-men-tum` rather than `in-du-men-tum` with the liturgical patterns.

**Comment by fradec** [comment]
That's right. I thought that was already the case, but only compounds with `super-` are already taken into account. I hope to be able to deal with the problem next week.
