### ISSUE TITLE
Word lists: verba delenda

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#46]
According to the *Gaffiot*, *abstare* is an intransitive verb; so there should be no passive forms except impersonal ones (third person singular).
The following words should be removed from the word lists:
- abstemini
- abstentur
- abster
- abstere
- absteris

**Comment by wehro** [comment]
I could not find the word *absiet* in any dictionary and I don't see how it can be derived from any word I found. If there is no explanation for this form, it should be removed from the word lists.

**Comment by wehro** [comment]
According to the general rules of the Latin third declension, the genitive plural of *adeps/adipis* is *adipum*. None of the dictionaries I consulted mentions the irregular form *adipium*. If there is no proof for this form, it should be deleted or changed to *adipum*.

**Comment by wehro** [comment]
The following words are not present in the common dictionaries and it is possibly better to remove them:
- adinspiratio
- ambitextus
- circumaspersus

**Comment by fradec** [comment]
I agree with your 3 first requests, I will clean up the wordlist. For `adipium`, I think it's a typing error, it should be `adipum`, you're right.

For `adinspiratio`, `ambitextus` and `circumaspersus`, I found them in Goelzer, they should not be deleted.

**Comment by wehro** [comment]
I think the following forms from the word list do not exist. They should rather be spelled *transibamini* etc.

- transebamini
- transebamur
- transebantur
- transebaris
- transebar
- transebere
- transeberis
- transebimini
- transebimur
- transebor
- transebuntur
- transemini
- transemur
- transendus
- transentor
- transentur
- transeremini
- transeremur
- transerentur
- transerer
- transetor

Furthermore, I have no explanation for the following form:
- transillit

**Comment by wehro** [comment]
The following letter pairs are no Latin words. It is unclear, why they appear in the test list.

- aa
- ya
- ye
- yi
- yu
- yy

**Comment by fradec** [comment]
They come from the initial diphthong file to guarantee the break between these letters whatever the situation. It is clear that they are not Latin words and there is no reason to keep them in the other files based on this list. But here I think we can keep them again.

**Comment by fradec** [comment]
> Furthermore, I have no explanation for the following form:
> 
>     * transillit

Neither me, I think it's a copy error which can be deleted.

**Comment by wehro** [comment]
The following words are not present in any dictionary I consulted. It is perhaps better to remove them.

- asycron
- præexistimo
- præteragavi

**Comment by wehro** [comment]
As far as I can see, the following forms do not exist:

- abstrasse, abstravi etc.
- abstrutus etc.
- catasceva (listed in the dictionaries as `catasceua` with `u`)

**Comment by wehro** [comment]
I could not verify the following words beginning with *super*:

- superelativus
- superisset (might be a perfect form of *super-eo*, but the dictionaries give no perfect of this word)
- superiungo
- supernumero
- superoperor (perhaps a misspelling of *super-operior*, passive of *super-operio*)
- superora, superore, superorem etc. (misspelling of *superior*)

**Comment by wehro** [comment]
> I think the following forms from the word list do not exist. They should rather be spelled _transibamini_ etc.
>     - transebamini
>     - transebamur
>     - transebantur
>     - …

I found a [French-speaking in grammar on archive.org](https://archive.org/details/PetitmanginLatinGrammaire/page/n75), showing an inflection scheme of the passive forms of the compounds of *ire*. This scheme is in accordance with [the rule I found in a German-speaking grammar](https://github.com/gregorio-project/hyphen-la/issues/38#issuecomment-439866523).

**Comment by wehro** [comment]
As far as I can see, there is no proof for a perfect form of *super-eo*. So `super-ii` and `super-ivi` may be removed form the word lists.
Furthermore, I could nowhere find the word `suprastruo`. I suggest to remove this as well.

**Comment by wehro** [comment]
The following forms cannot derive from *per-eo* or *per-jero* or any other verb. I think they are typing errors that should be deleted or corrected.

- perieim
- perieimus
- perieint
- perieis
- perieit
- perieitis
- perieo
- perieunt

**Comment by wehro** [comment]
*proditus* is a mere participle of *prodo*. It is not used as an adjective with comparative or superlative forms (according to ThLL).
So the following forms should be deleted:
- proditior
- proditiora
- proditiore
- proditiorem
- proditiores
- proditiori
- proditioribus
- proditioris
- proditissimus (with inflected forms)

**Comment by wehro** [comment]
*obœdio* is an intransitive verb, which means that it can have no passive forms except impersonal ones. The following forms are not necessary and may be removed from the word lists:
- obœdiamini
- obœdiamur
- obœdiantur
- obœdiar
- obœdiare
- obœdiaris
- obœdiebamini
- obœdiebamur
- obœdiebantur
- obœdiebar
- obœdiebare
- obœdiebaris
- obœdiemini
- obœdiemur
- obœdientur
- obœdiere
- obœdieris
- obœdimini
- obœdimur
- obœdior
- obœdiremini
- obœdiremur
- obœdirentur
- obœdirer
- obœdirere
- obœdireris
- obœdiri
- obœdiris
- obœdiuntur

**Comment by wehro** [comment]
> According to the _Gaffiot_, _abstare_ is an intransitive verb; so there should be no passive forms except impersonal ones (third person singular).
> The following words should be removed from the word lists:
> 
>     * abstemini
> 
>     * abstentur
> 
>     * abster
> 
>     * abstere
> 
>     * absteris

Some supplements:
- abstabamini
- abstabamur
- abstabantur
- abstabar
- abstabare
- abstabaris
- abstabere
- abstaberis
- abstabimini
- abstabimur
- abstabor
- abstabuntur
- abstamini
- abstamur
- abstaremini
- abstaremur
- abstarentur
- abstarer
- abstarere
- abstareris
- abstari
- abstaris
- abstator
- abstemur
- abstemus
- abstor

**Comment by wehro** [comment]
I propose to remove the following forms from the word lists:

- `Aposcopevon`: is written with *u* in all dictionaries I consulted: *aposcopeuon*.
- `aspharagos`: is not present in any dictionary I consulted.
- `Cœlesyriæ` and `Cœlesyriam`: as far as I can see from different dictionaries, *Coele Syria* is always written in two words.
- `fœteris`: theoretically, this is a passive form of `fœteo`, which is however intransitive, which means that it can have only impersonal passive forms.
- `intericunto`: obviously a misspelling of *intericiunto*.
- `perieam`, `perieas`, `perieat`, `perieamus`, `perieatis`, `perieant`: possibly misspellings of the subjunctive forms of *per-eo*, which should be *peream*, *pereas* etc.
- `posfuturus` and declensed forms: an imaginary future participle of *possum*.
- `præposfuturus`: also imaginary from *præpossum*.
- `prodiciius`: probably a misspelling of *prodicius*.
- `sagestrum`: probably a misspelling of *segestrum*, alternative of *segestre*.
- `subie`: possibly a wrong vocative of *subium* or a wrong form of *sub-eo*.
- `superaffero`, `superaffluo`: These verbs are not present in any dictionary I consulted.

**Comment by fradec** [comment]
> I think the following forms from the word list do not exist. They should rather be spelled _transibamini_ etc.

It's done.

**Comment by fradec** [comment]
> I could not verify the following words beginning with _super_:
> 
>     * superelativus
> 
>     * superisset (might be a perfect form of _super-eo_, but the dictionaries give no perfect of this word)
> 
>     * superiungo
> 
>     * supernumero
> 
>     * superoperor (perhaps a misspelling of _super-operior_, passive of _super-operio_)
> 
>     * superora, superore, superorem etc. (misspelling of _superior_)

These words come from Goelzer, except for superisset and superora etc.

**Comment by fradec** [comment]
> The following words are not present in any dictionary I consulted. It is perhaps better to remove them.
> 
>     * asycron
> 
>     * præexistimo
> 
>     * præteragavi

Ok for `præteragavi`, but not for `præexistimo` which can be found in Goelzer. Where did you see `asycron`? There is a `ascyron` in the list, which can also be found in Goelzer.

**Comment by fradec** [comment]
Partly because I had to put the work on hold, I find that this issue is not easy to follow, there are too many different topics. With separate issues, it would be easier to navigate in the different tasks after a period of absence (which may be my case ...). I would be in favor of opening issues by prefix that can gather together the neighboring words. It's the same for #38.

**Comment by wehro** [comment]
OK, you are right. I will close the two long issues and open new ones for all remaining problems.

**Comment by wehro** [comment]
> Ok for `præteragavi`, but not for `præexistimo` which can be found in Goelzer. Where did you see `asycron`? There is a `ascyron` in the list, which can also be found in Goelzer.

`asycron` was a reading error of mine.

It is clear, that a word that can be found in any dictionary shall not be removed. To be sure, I report all words not occuring in the dictionaries to which I have access. I always appreciate your comments.
