### ISSUE TITLE
prodest and other inflected forms of prosum

### ISSUE THREAD

**Issue by bbloomf** [gregorio-project/hyphen-la#47]
I noticed that prodest was syllabifying as pro-dest, so I checked all the forms of prosum that begin with prod- and most of them don't keep the D with the first syllable:

pro-des
pro-dest
pro-des-tis
pro-des-tis
pro-de-ram
pro-de-ras
pro-de-rat
pro-de-ra-mus
pro-de-ra-tis
pro-de-rant
pro-de-ro
pro-de-ris
pro-de-re
pro-de-rit
pro-de-ri-mus
pro-de-ri-tis
pro-de-runt
pro-des-te
pro-des-to
pro-des-to-te

But the ones beginning with prodess- do work:

prod-es-se
prod-es-sem
prod-es-ses
prod-es-set
prod-es-se-mus
prod-es-se-tis
prod-es-sent

**Comment by bbloomf** [comment]
I checked the other prefixed sum verbs, and the same forms of intersum are also affected

**Comment by fradec** [comment]
Thank you for your vigilance! I will try to review the `sum` compounds in the coming weeks. Words beginning with `inter` or `prod` are also on the program, but it will probably take some time ...

**Comment by fradec** [comment]
I counted 15 sum compounds:

- absum
- adsum
- coadsum
- consum
- desum
- insum
- intersum
- obsum
- possum
- præpossum
- præsum
- prætersum
- prosum
- subsum
- supersum

thank you for telling me if there are others.

It is useless to take care of `consum` which has only very few forms. `obsum` and `supersum` have already been reviewed, leaving only 12 compounds. After first researches, it requires a review of the neighboring words that begin with:

- co-
- inter(e)-
- præpot-
- prod-

**Comment by fradec** [comment]
I synchronize the hyphenator page just now, although the work is not finished: it remains `insum` and `intersum` that will ask for more work, but at least `prod-` is fixed.

**Comment by fradec** [comment]
I had forgotten the very rare verb `prætero`, which is now taken into account. I hope to be able to deal with `intersum` and `insum` soon.

**Comment by fradec** [comment]
It's now ok.
