### ISSUE TITLE
Broken Case

### ISSUE THREAD

**Issue by benyanke** [gregorio-project/hyphen-la#5]
Laus tibi, Domine, rex aeternae gloriae.

Goes to:

Laus() ti()bi,() Do()mi()ne,() rex() a()e()ter()na()e() glo()ri()a()e.()

Of course, in Aeternae and gloriae, there are additional syllables.

**Comment by eroux** [comment]
Indeed, the hyphenation only works with correctly spelled liturgical latin: *æternæ gloriæ*
