### ISSUE TITLE
obsoletus/obsolesco/obsoleficio

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#52]
These words derive from *ob(s)* and *alo*. The hyphenation should be `obs-o-le-tus`/`obs-o-les-co`/`obs-o-le-fi-ci-o`.

**Comment by wehro** [comment]
The same applies to *absoleo*: `abs-o-le-o`.

**Comment by fradec** [comment]
I followed Goelzer who gives `ob` + `soleo` as origin. But I can change.

Where did you find `obs` + `alo`?

**Comment by fradec** [comment]
There may be 20 Gaffiot entries involved:

- absoleo
- adsoleo
- exsolens
- exsolesco
- exsoletus
- inobsoletus
- insolens
- insolenter
- insolentia
- insoleo
- insolesco
- obsolefacio
- obsolefactus
- obsolefio
- obsolesco
- obsolete
- obsoleto
- obsoletus
- obsolevi
- perinsolens

with a quick search, but it should be seen more closely.

**Comment by wehro** [comment]
> I followed Goelzer who gives `ob` + `soleo` as origin. But I can change.

What edition of Goelzer do you use? I was able to buy a very cheap reprint of a 1928 edition, but unfortunately, no etymologies are given there.

> Where did you find `obs` + `alo`?

This etymology is given in *Stowasser*, a popular Latin-German school dictionary (edition of 1998). *absoleo* is not present there, but according to [*Georges*](http://www.zeno.org/Georges-1913/K/Georges-1913-01-0032), it is a vulgar form of *obsoleo*.

**Comment by wehro** [comment]
I doubt that all the 20 word in the list have the same origin. *s* can be an epenthesis only after *ab*, *ob*, and *sub*. In other cases, it must be part of the second element.

**Comment by fradec** [comment]
> > I followed Goelzer who gives `ob` + `soleo` as origin. But I can change.
> 
> What edition of Goelzer do you use? I was able to buy a very cheap reprint of a 1928 edition, but unfortunately, no etymologies are given there.

My edition has no date, but it is the 11th, which follows shortly the death of the author, so it is probably that of 1934. The definition of `obsolesco` is: to wear, to fall into disuse, weaken, lose value

> > Where did you find `obs` + `alo`?
> 
> This etymology is given in _Stowasser_, a popular Latin-German school dictionary (edition of 1998). _absoleo_ is not present there, but according to [_Georges_](http://www.zeno.org/Georges-1913/K/Georges-1913-01-0032), it is a vulgar form of _obsoleo_.

The Gaffiot also refers to `obsoleo`, Goelzer does not have it.

[Jacob](https://archive.org/details/LexiquetymologiqueLatin-franais1/page/n105) have an `absolesco` — but no `absoleo` (Goelzer has none of the two) — and give for it the etymology `ab` + `soleo`, while he gives the same etymology than yours for `obsole(sc)o`: `ob` + `olesco`.

I don't know what to think with such differences.

**Comment by wehro** [comment]
The *Thesaurus linguae latinae* gives the following etymology of *obsolesco*:

> ab *ob* et *solere*, cf. *desuescere* et *exolescere* (ThLL IX, 2, 1968–1981)

The etymological dictionary of Ernout and Meillet states for this word:

> Étymologie et histoire obscures. Ni l'explication par **obs-olēscō*, ni celle par **ob-solēscō* ne satisfont. Il a dû y avoir, comme pour *exolētus*, *exolēscō*, avec lesquels *obsolēscō*, *obsolētus* sont intimement liés pour le sens, des contaminations et des influences qu'on entrevoit sans pouvoir les préciser.

So we see that even the experts disagree or are not sure. I think it is better, to ignore the etymology and to follow the general rules in this case. This would mean that the current hyphenations are kept.
Please close if you agree.

**Comment by fradec** [comment]
Ok, I agree with you, it seems to be the most reasonable solution.

Thank you for your accurate research!
