### ISSUE TITLE
perendie

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#56]
The etymology of *perendie* is uncertain. So it should be hyphenated according to the general rules: `pe-ren-di-e`.

**Comment by fradec** [comment]
Jacobs give `peremptus` + `dies`. As `peremptus` comes from `perimo` (`per` +` emo`), I think we have to hyphenate `per-en-di-e`.

**Comment by fradec** [comment]
Depending on the rule followed, it will also take into account all the following words (derived or close in the dictionary):

- comperendinatio
- comperendinatus
- comperendino
- comperendinus
- perendie
- perendinatio
- perendinus
- perenne
- perennis
- perenniservus
- perennitas
- perenniter
- perenno
- perenticida

only `perenticida` must have a *classic* hyphenation because it comes from `pera` + `cædo`.

**Comment by wehro** [comment]
> Jacobs give `peremptus` + `dies`. As `peremptus` comes from `perimo` (`per` +` emo`), I think we have to hyphenate `per-en-di-e`.

I would not trust *Jacob* as the only source. This work is rather old and it often differs from other sources in difficult cases.

The ThLL (volume X.1, 1982–1997) says concerning the etymology:

> cf. *-diē* adverbiorum *ho-, cottī, postrī-diē* etc.; pars prior *peren-* nondum explanata fere indicationem intervalli continere putatur, cf. e. g. theod. *über-morgen*; haud magis perspicitur adi. cognatum *perendinus* (vox prisca ? v. infra l. 63), neque coniunctio cum *ἔνη* adhuc potuit probari.

The etymological dictionary of Ernout/Meillet states:

> De **peren-diē* « le jour par delà » ; la comparaison de *prīdiē, postrīdiē* montre qu'il n'y a qu'un élément dans *peren-* et qu'on ne saurait le décomposer en **per-en-diē*. Comme *ho-diē*, le premier élément *peren-* est un thème nu, normal dans un premier terme de composé.

I think these statements justify the hyphenation `pe-ren-di-e`.

**Comment by wehro** [comment]
> Depending on the rule followed, it will also take into account all the following words (derived or close in the dictionary):

The word of this list belong to three different groups.

1. All words containing `perenn` derive from *per* + *annum* without any doubt. So the hyphenation is `per-en-nis` etc.
2. All words containing `perend` are cognate to *perendie*. The hyphenation should be `pe-ren-die` etc. as suggested above.
3. *perenticida* is cognate to none of the other words. The hyphenation is `pe-ren-ti-ci-da` as you already stated.

**Comment by fradec** [comment]
Your explanation is clear and precise. So it's perfect, I correct the patterns. So, only words with 2 `n` keep the `per-` hyphenation.
