### ISSUE TITLE
Ephraim, Ephraïm

### ISSUE THREAD

**Issue by bbloomf** [gregorio-project/hyphen-la#7]
Ephraim syllabifies to: E()ph()raim() or E()ph()ra()ïm() when given with a diaeresis over the i.

"ph" cannot be a syllable by itself because it has no vowel.  I'm not sure whether the syllabification should be E()phra()im or Eph()ra()im

**Comment by OldClaudio** [comment]
I Think the correct hyphenatin with Latin rules of this non Latin name
should be E-phra-im. But I am not a latinist.

**Comment by egorsmkv** [comment]
The char ï also exists in Ukrainian language

**Comment by fradec** [comment]
E-phra-im seems good for me. The ï is not necessary in Latin, because all the vowels are pronounced. But it's true that sometimes it can be found Ephraïm.
For this repo, is it necessary to keep both versions?

**Comment by fradec** [comment]
Biblical proper names that include the 'phr' block are:

- Epaphra
- Epaphras
- Epaphródito
- Epaphróditum
- Ephraim
- Ephrata
- Ephratæ
- Ephratam
- Ephratha
- Ephrathǽi
- Ephrathǽus
- Ephrée
- Ephrónis

they should be hyphened as follows:

- E-pa-phra
- E-pa-phras
- E-pa-phro-di-to
- E-pa-phro-di-tum
- E-phra-im
- E-phra-ta
- E-phra-tæ
- E-phra-tam
- E-phra-tha
- E-phra-thæ-i
- E-phra-thæ-us
- E-phre-e
- E-phro-nis

**Comment by fradec** [comment]
It seems to be necessary to add a new pattern for the *phr* block and to modify the *2i2m.* pattern (line 1405).

I propose to add *ph8r*, and to replace *2i2m.* by *r2i2m.*, *t2i2m.* and *a1i2m.* which make it possible to get what you want.

**Comment by eroux** [comment]
good job, thanks!
