### ISSUE TITLE
pro-

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#74]
*proditus* is a mere participle of *pro-do*. It is not used as an adjective with comparative or superlative forms (according to ThLL).
So the following forms should be deleted from the word lists:

- proditior
- proditiora
- proditiore
- proditiorem
- proditiores
- proditiori
- proditioribus
- proditioris
- proditissimus (with inflected forms)

**Comment by fradec** [comment]
Ok. Done.

**Comment by wehro** [comment]
The form `prodiciius` does not exist. It is probably a misspelling of *prodicius* and should be corrected in the test lists.

**Comment by fradec** [comment]
Correct. I will do it.
