### ISSUE TITLE
fœteo

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#79]
*fœteo* ›avoir une odeur fétide, sentir mauvais‹ is an intransitive verb. The following passive forms may be removed from the word lists:
- fœ-te-a-mi-ni
- fœ-te-a-mur
- fœ-te-an-tur
- fœ-te-ar
- fœ-te-a-re
- fœ-te-a-ris
- fœ-te-ba-mi-ni
- fœ-te-ba-mur
- fœ-te-ban-tur
- fœ-te-bar
- fœ-te-ba-re
- fœ-te-ba-ris
- fœ-te-be-re
- fœ-te-be-ris
- fœ-te-bi-mi-ni
- fœ-te-bi-mur
- fœ-te-bor
- fœ-te-bun-tur
- fœ-te-mi-ni
- fœ-te-mur
- fœ-ten-tur
- fœ-te-or
- fœ-te-re-mi-ni
- fœ-te-re-mur
- fœ-te-ren-tur
- fœ-te-rer
- fœ-te-re-re
- fœ-te-re-ris
- fœ-te-ris

**Comment by fradec** [comment]
Done.
