### ISSUE TITLE
sagestrum

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#82]
The word `sagestrum` does not exist. It is probably a misspelling of *segestrum*, an alternative form of *segestre*.

**Comment by fradec** [comment]
I found it in my Goelzer:
*sǎgestrum, i (sagum), n.* blanket, carpet

**Comment by wehro** [comment]
OK, so this is another rare word only listed in Goelzer.

By the way: I have added all relevant dictionaries to our [bibliography](https://github.com/gregorio-project/hyphen-la/tree/master/doc#bibliography). Could you add your edition of Goelzer there? It is obviously more comprehensive than the 1928 edition already listed.

**Comment by fradec** [comment]
It is a good idea, but I will not be able to put a certain date because my copy does not have one, I think however that it is that of 1934, that's what I will indicate.
