### ISSUE TITLE
Rare words

### ISSUE THREAD

**Issue by wehro** [gregorio-project/hyphen-la#84]
There are some words in `wordlist-liturgical.txt` which are not listed in the dictionaries to which I have access. I suppose they are all taken from a comprehensive edition of *Goelzer*:
- præexistimo
- superaffero
- superaffluo
- superelativus
- superiungo
- supernumero
- suprastruo

I need some information to be able to add these words to the word list I use for the generation of the classical patterns.

For `superelativus`: Is it a noun or an adjective? If it is a noun, which genitive is given?

For the others, which are obviously verbs: Which perfect and supine forms are given? Are they transitive or intransitive?

For all: Are there any vowel lengths given?

**Comment by fradec** [comment]
- **præ-existǐmo**, ās, āre, tr. Présumer.
- **sǔpěr-affěro**, fers, ferre, tr. Apporter, causer par surcroît.
- **sǔpěr-afflǔo**, ǐs, ěre, intr. Surabonder.
- **sǔpěr-ēlātīvus**, a, um (*super, effero*), adj. Qui exalte.
- **sǔpěr-jungo**, ǐs, ěre, tr. Ajouter en sus.
- **sǔpěr-nǔměro**, ās, āre, tr. Énumérer.
- **suprā-strǔo**, ǐs, ěre, tr. Édifier dessus.

**Comment by wehro** [comment]
Thank you, that's great!

Perhaps you can help me with some other words. Claudio has listed a couple of difficult words in the [present TeX version of the classical patterns](https://github.com/gregorio-project/hyphen-la/blob/9faac7e7a49450e79d0947e5baf71b649cff75c5/patterns/tex/hyph-la-x-classic.tex). I try to take over all of them to the new word list `index_verborum`, but I could not verify some of them. They might be present in Goelzer.
- redarduo
- respargo
- restilio
- subodorare
- susscribo
- transoceanus
- transusque
- tranverbero
- Zaieucus

**Comment by fradec** [comment]
I search in Goelzer, here are the results:

- redarduo → no match (redarguo?)
- respargo → no match, but:
   - **respergo**, ǐs, spersi, spersum, ěre (re, spargo), tr. Éclabousser, arroser, tacher.
   - **respergo**, gǐnis (respergo), f. Action de mouiller, souillure, tache, éclaboussure.
- restilio → **re-stillo**, ās, āvi, ātum, āre, tr. et intr. Introduire goutte à goutte
- subodorare → no match
- susscribo → no match
- transoceanus → no match
- transusque → no match
- tranverbero → **trans-verběro**, ās, āvi, ātum, āre, tr. Percer en frappant, transpercer.
- Zaieucus → **Zaleucus**, i, m. (with a L)

**Comment by wehro** [comment]
OK, most of these words seem to be typing errors.
Thank you!
